### ISSUE TITLE
Add the ability to sample angles anisotropically when generating toy data

### ISSUE THREAD

**Issue by mmechtley** [davidwhogg/DiffractionMicroscopy#12]
The model has an implicit prior that the projections / viewing directions are isotropically distributed. However, for real microscopy data this may not be the case – could be weak magnetic fields, etc. that cause the molecules to have a preferred orientation.

Maybe provide several ways, progressively worse. A really simple one would be to pick random vectors the naive wrong way! (just pick spherical phi/theta uniformly).

**Comment by davidwhogg** [comment]
+1

**Comment by davidwhogg** [comment]
I have a very simple implementation; it involves _distorting_ the vectors you get before you normalize xhat. What you do is you take every xhat draw, and you magnify slightly it's 0-axis component (multiply it up by a factor, like 1.1, or 0.9) (or it's 1-axis or 2-axis component) before you normalize it and generate yhat. This will produce a quadrupole distortion (which I think is the most relevant, though I know how to make a dipole distortion too!).

**Comment by mmechtley** [comment]
Basic functionality now implemented. Support for both dipole and quadrupole distortions, and added a function visualize the angle sampling to ensure these are working as intended. Dipole shifts xhat vectors along one axis before normalizing. Quadrupole scales xhat vectors along one axis before normalizing.

**Comment by davidwhogg** [comment]
I'm closing for now.
